### ISSUE TITLE
Current win release needs a lot of external dlls for running (please create a static build)

### ISSUE THREAD

**Issue by rwbc** [DanSamek/Sentinel#5]
**missing in release version 1.01 for win (in Win11 Pro):**
```
MSVCP140D.dll
ucrtbased.dll
VCRUNTIME140D.dll
VCRUNTIME140_1D.dll
```

Therefore I compiled my own win build in msys2.
https://rwbc-chess.de/Downloads/Engines/temp/Sentinel.7z

There was still a little fix needed with a missing include (cstdint) in move.h.

Then compiling went smoothly. I created a static build for my native hardware (Ryzen7 5700G) and enabled -O3 instead of -O2.
```

Admin@ESPRESSO MINGW64 ~/Sentinel
# cmake -DCMAKE_BUILD_TYPE=Release
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- Building for: Ninja
-- The C compiler identification is GNU 14.2.0
-- The CXX compiler identification is GNU 14.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (1.3s)
-- Generating done (0.0s)
-- Build files have been written to: C:/msys64/home/Admin/Sentinel

Admin@ESPRESSO MINGW64 ~/Sentinel
# ninja -j 4
[19/19] Linking CXX executable Sentinel.exe
```

Can you verify that the output (from cmd) below is correct?
```

uci
id name Sentinel-1.0
id author Daniel Samek

option name Hash type spin default 128 min 1 max 30000
uciok
isready
5592405
24
readyok
position startpos
go wtime 120000 btime 120000 winc 2000 binc 2000
info score cp 73 depth 1 nodes 27 time 0 nps 27 move e2e3 pv e2e3
info score cp 0 depth 2 nodes 136 time 1 nps 136000 move e2e3 pv e2e3 e7e6
info score cp 58 depth 3 nodes 445 time 2 nps 222500 move e2e3 pv e2e3 e7e6 g1f3
info score cp 0 depth 4 nodes 1169 time 3 nps 389666 move e2e3 pv e2e3 e7e6 g1f3 g8f6
info score cp 41 depth 5 nodes 2149 time 5 nps 429800 move e2e3 pv e2e3 e7e6 b1c3 g8f6 g1f3
info score cp 0 depth 6 nodes 10067 time 10 nps 1006700 move b1c3 pv b1c3 e7e6 e2e3 b8c6 g1f3 g8f6
info score cp 31 depth 7 nodes 18486 time 15 nps 1232400 move g1f3 pv g1f3 e7e6 e2e3 g8f6 b1c3 b8c6 d2d4
info score cp 13 depth 8 nodes 46414 time 30 nps 1547133 move g1f3 pv g1f3 g8f6 d2d4 d7d5 b1c3 b8c6 e2e3 e7e6
info score cp 30 depth 9 nodes 63602 time 39 nps 1630820 move g1f3 pv g1f3 e7e6 e2e3 b8c6 b1c3 g8f6 d2d4 d7d5 h2h3
info score cp 13 depth 10 nodes 166643 time 87 nps 1937709 move g1f3 pv g1f3 g8f6 b1c3 d7d5 e2e3 b8c6 d2d4 e7e6 h2h3 h7h6
info score cp 34 depth 11 nodes 278222 time 139 nps 2001597 move g1f3 pv g1f3 b8c6 b1c3 d7d5 e2e3 g8f6 d2d4 f6e4 f1e2 e4c3 b2c3
info score cp 19 depth 12 nodes 960874 time 451 nps 2130541 move e2e4 pv e2e4 d7d5 e4e5 c7c5 g1f3 b8c6 b1c3 c8g4 h2h3 g4f3 d1f3 e7e6
info score cp 24 depth 13 nodes 1159094 time 541 nps 2142502 move b1c3 pv b1c3 d7d5 d2d4 b8c6 g1f3 g8f6 e2e3 e7e6 f1d3 f8d6 e1g1 e8g8 e3e4
info score cp 22 depth 14 nodes 2172908 time 1027 nps 2115781 move d2d4 pv d2d4 g8f6 g1f3 d7d5 c1f4 c7c5 b1d2 c5d4 f3d4 h7h6 e2e3 b8c6 f1b5 c8d7
info score cp 47 depth 15 nodes 5640012 time 2696 nps 2091992 move e2e4 pv e2e4 e7e5 b1c3 b8c6 g1f3 g8f6 d2d4 e5d4 f3d4 f8b4 d4c6 b7c6 d1d4 b4c3 d4c3 e8g8
info score cp 40 depth 16 nodes 8086488 time 3898 nps 2075054 move e2e4 pv e2e4 d7d5 e4d5 c7c6 g1f3 c6d5 d2d4 b8c6 f1e2 g8f6 e1g1 e7e6 c2c4 f8d6 c4d5 e6d5
info score cp 41 depth 17 nodes 10240964 time 4961 nps 2064294 move e2e4 pv e2e4 d7d5 e4d5 c7c6 g1f3 c6d5 d2d4 b8c6 f1e2 g8f6 e1g1 c8f5 c2c4 d5c4 e2c4 a8c8 b1c3
TT used:1843469 _nodesVisited:15508428
bestmove e2e4
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . P . . .
. . . . . . . .
P P P P . P P P
R N B Q K B N R


```
BTW I noticed after 'go depth x' it does not stop at 'x' but goes on calculating. I guess it's not implemented yet and
you do go infinite instead? (was too lazy to check the code)

Guenther

**Comment by DanSamek** [comment]
> **missing in release version 1.01 for win (in Win11 Pro):**
> 
> ```
> MSVCP140D.dll
> ucrtbased.dll
> VCRUNTIME140D.dll
> VCRUNTIME140_1D.dll
> ```
> 
> Therefore I compiled my own win build in msys2. https://rwbc-chess.de/Downloads/Engines/temp/Sentinel.7z
> 
> There was still a little fix needed with a missing include (cstdint) in move.h.
> 
> Then compiling went smoothly. I created a static build for my native hardware (Ryzen7 5700G) and enabled -O3 instead of -O2.
> 
> ```
> 
> Admin@ESPRESSO MINGW64 ~/Sentinel
> # cmake -DCMAKE_BUILD_TYPE=Release
> CMake Warning:
>   No source or binary directory provided.  Both will be assumed to be the
>   same as the current working directory, but note that this warning will
>   become a fatal error in future CMake releases.
> 
> 
> -- Building for: Ninja
> -- The C compiler identification is GNU 14.2.0
> -- The CXX compiler identification is GNU 14.2.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Configuring done (1.3s)
> -- Generating done (0.0s)
> -- Build files have been written to: C:/msys64/home/Admin/Sentinel
> 
> Admin@ESPRESSO MINGW64 ~/Sentinel
> # ninja -j 4
> [19/19] Linking CXX executable Sentinel.exe
> ```
> 
> Can you verify that the output (from cmd) below is correct?
> 
> ```
> 
> uci
> id name Sentinel-1.0
> id author Daniel Samek
> 
> option name Hash type spin default 128 min 1 max 30000
> uciok
> isready
> 5592405
> 24
> readyok
> position startpos
> go wtime 120000 btime 120000 winc 2000 binc 2000
> info score cp 73 depth 1 nodes 27 time 0 nps 27 move e2e3 pv e2e3
> info score cp 0 depth 2 nodes 136 time 1 nps 136000 move e2e3 pv e2e3 e7e6
> info score cp 58 depth 3 nodes 445 time 2 nps 222500 move e2e3 pv e2e3 e7e6 g1f3
> info score cp 0 depth 4 nodes 1169 time 3 nps 389666 move e2e3 pv e2e3 e7e6 g1f3 g8f6
> info score cp 41 depth 5 nodes 2149 time 5 nps 429800 move e2e3 pv e2e3 e7e6 b1c3 g8f6 g1f3
> info score cp 0 depth 6 nodes 10067 time 10 nps 1006700 move b1c3 pv b1c3 e7e6 e2e3 b8c6 g1f3 g8f6
> info score cp 31 depth 7 nodes 18486 time 15 nps 1232400 move g1f3 pv g1f3 e7e6 e2e3 g8f6 b1c3 b8c6 d2d4
> info score cp 13 depth 8 nodes 46414 time 30 nps 1547133 move g1f3 pv g1f3 g8f6 d2d4 d7d5 b1c3 b8c6 e2e3 e7e6
> info score cp 30 depth 9 nodes 63602 time 39 nps 1630820 move g1f3 pv g1f3 e7e6 e2e3 b8c6 b1c3 g8f6 d2d4 d7d5 h2h3
> info score cp 13 depth 10 nodes 166643 time 87 nps 1937709 move g1f3 pv g1f3 g8f6 b1c3 d7d5 e2e3 b8c6 d2d4 e7e6 h2h3 h7h6
> info score cp 34 depth 11 nodes 278222 time 139 nps 2001597 move g1f3 pv g1f3 b8c6 b1c3 d7d5 e2e3 g8f6 d2d4 f6e4 f1e2 e4c3 b2c3
> info score cp 19 depth 12 nodes 960874 time 451 nps 2130541 move e2e4 pv e2e4 d7d5 e4e5 c7c5 g1f3 b8c6 b1c3 c8g4 h2h3 g4f3 d1f3 e7e6
> info score cp 24 depth 13 nodes 1159094 time 541 nps 2142502 move b1c3 pv b1c3 d7d5 d2d4 b8c6 g1f3 g8f6 e2e3 e7e6 f1d3 f8d6 e1g1 e8g8 e3e4
> info score cp 22 depth 14 nodes 2172908 time 1027 nps 2115781 move d2d4 pv d2d4 g8f6 g1f3 d7d5 c1f4 c7c5 b1d2 c5d4 f3d4 h7h6 e2e3 b8c6 f1b5 c8d7
> info score cp 47 depth 15 nodes 5640012 time 2696 nps 2091992 move e2e4 pv e2e4 e7e5 b1c3 b8c6 g1f3 g8f6 d2d4 e5d4 f3d4 f8b4 d4c6 b7c6 d1d4 b4c3 d4c3 e8g8
> info score cp 40 depth 16 nodes 8086488 time 3898 nps 2075054 move e2e4 pv e2e4 d7d5 e4d5 c7c6 g1f3 c6d5 d2d4 b8c6 f1e2 g8f6 e1g1 e7e6 c2c4 f8d6 c4d5 e6d5
> info score cp 41 depth 17 nodes 10240964 time 4961 nps 2064294 move e2e4 pv e2e4 d7d5 e4d5 c7c6 g1f3 c6d5 d2d4 b8c6 f1e2 g8f6 e1g1 c8f5 c2c4 d5c4 e2c4 a8c8 b1c3
> TT used:1843469 _nodesVisited:15508428
> bestmove e2e4
> r n b q k b n r
> p p p p p p p p
> . . . . . . . .
> . . . . . . . .
> . . . . P . . .
> . . . . . . . .
> P P P P . P P P
> R N B Q K B N R
> ```
> 
> BTW I noticed after 'go depth x' it does not stop at 'x' but goes on calculating. I guess it's not implemented yet and you do go infinite instead? (was too lazy to check the code)
> 
> Guenther

Ad. Can you verify that the output (from cmd) below is correct?   
Yes its correct
*One day I will remove debug outputs, sorry for the mess*
  
Ad. 'go depth x' 
`go depth` isn't implemented yet, it will run as `go infinite`.
  
Ad. static build
I created a static build, hopefully it will be okay.

Thanks!
